export const TOKENS = {
  // Infrastructure
  DATABASE_CONNECTION: Symbol('DATABASE_CONNECTION'),
  PRISMA_CLIENT: Symbol('PRISMA_CLIENT'),

  // Configuration
  ENVIRONMENT_CONFIG: Symbol('ENVIRONMENT_CONFIG'),
  DATABASE_CONFIG: Symbol('DATABASE_CONFIG'),

  // Shared Services
  PASSWORD_SERVICE: Symbol('PASSWORD_SERVICE'),
  JWT_SERVICE: Symbol('JWT_SERVICE'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),

  // User Module
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  CREATE_USER_USE_CASE: Symbol('CREATE_USER_USE_CASE'),
  GET_USERS_USE_CASE: Symbol('GET_USERS_USE_CASE'),
  GET_USER_BY_ID_USE_CASE: Symbol('GET_USER_BY_ID_USE_CASE'),
  UPDATE_USER_USE_CASE: Symbol('UPDATE_USER_USE_CASE'),
  DELETE_USER_USE_CASE: Symbol('DELETE_USER_USE_CASE'),
  USERS_CONTROLLER: Symbol('USERS_CONTROLLER'),

  // Auth Module
  AUTH_REPOSITORY: Symbol('AUTH_REPOSITORY'),
  LOGIN_USE_CASE: Symbol('LOGIN_USE_CASE'),
  REFRESH_TOKEN_USE_CASE: Symbol('REFRESH_TOKEN_USE_CASE'),
  LOGOUT_USE_CASE: Symbol('LOGOUT_USE_CASE'),
  AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),

  // Role Module
  ROLE_REPOSITORY: Symbol('ROLE_REPOSITORY'),
  CREATE_ROLE_USE_CASE: Symbol('CREATE_ROLE_USE_CASE'),
  GET_ROLES_USE_CASE: Symbol('GET_ROLES_USE_CASE'),
  GET_ROLE_BY_ID_USE_CASE: Symbol('GET_ROLE_BY_ID_USE_CASE'),
  UPDATE_ROLE_USE_CASE: Symbol('UPDATE_ROLE_USE_CASE'),
  DELETE_ROLE_USE_CASE: Symbol('DELETE_ROLE_USE_CASE'),

  // Permission Module
  PERMISSION_REPOSITORY: Symbol('PERMISSION_REPOSITORY'),
  CREATE_PERMISSION_USE_CASE: Symbol('CREATE_PERMISSION_USE_CASE'),
  GET_PERMISSIONS_USE_CASE: Symbol('GET_PERMISSIONS_USE_CASE'),
  GET_PERMISSION_BY_ID_USE_CASE: Symbol('GET_PERMISSION_BY_ID_USE_CASE'),
  UPDATE_PERMISSION_USE_CASE: Symbol('UPDATE_PERMISSION_USE_CASE'),
  DELETE_PERMISSION_USE_CASE: Symbol('DELETE_PERMISSION_USE_CASE'),
} as const;

export type TokenType = (typeof TOKENS)[keyof typeof TOKENS];
